import Axios from 'axios'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'
import Input from '../components/elements/input'
import Api from '../core/services/api'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [ password, setPassword ] = useState('');
  const [ email, setEmail ] = useState('');
  
  function handleSubmit(event: any) {
    Axios.post('localhost:3333/login', {
      password,
      email
    }).then(res => {
      console.log(res.data)
    }).catch(error => {
      console.log(error)
    })
    event.preventDefault();
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Você precisa fazer login</h1>

      <form onSubmit={handleSubmit}>
        <Input
          type="email"
          name="email"
          label="Digite seu email"
          value={email}
          setValue={setEmail}
        />
      
        <Input
          type="password"
          name="password"
          label="Digite sua senha"
          value={password}
          setValue={setPassword}
        />

        <input type="submit" value="Fazer Login" />
      </form>
    </div>
  )
}

export default Home
